# Generated by Django 4.1.10 on 2024-03-18 16:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationExt',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('title', models.CharField(max_length=128, verbose_name='应用显示标题')),
                ('subject_identifier', models.CharField(max_length=64, verbose_name='主体标识符')),
                ('q_a_component', models.CharField(default='', max_length=64, verbose_name='问答组件')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application'))
            ],
            options={
                'db_table': 'application_ext',
            },
        ),
        migrations.CreateModel(
            name='ApplicationQaText',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('subject_identifier', models.CharField(max_length=64, verbose_name='主体标识符', default='global')),
                ('q_a_text', models.CharField(max_length=128, verbose_name='问答文本')),
            ],
            options={
                'db_table': 'application_qa_text',
            },
        ),
        migrations.CreateModel(
            name='ApplicationQaTextMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('application_qa_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_ext.ApplicationQaText')),
            ],
            options={
                'db_table': 'application_ext_qa_text_mapping',
            },
        ),
    ]
    