# Generated by Django 4.2.20 on 2025-07-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_ext', '0004_application_ext_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationext',
            name='q_a_component',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='问答组件'),
        ),
        migrations.AlterField(
            model_name='applicationext',
            name='subject_identifier',
            field=models.CharField(default='', max_length=64, verbose_name='主体标识符'),
        ),
    ]
